name: Send Daily Quote Email

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Runs daily at midnight UTC

jobs:
  send_email_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Install Ollama
      run: |
        echo "Installing Ollama CLI..."
        curl -fsSL https://ollama.com/install.sh | sh
        echo "Verifying Ollama installation..."
        which ollama || (echo "Ollama not found in PATH" && exit 1)

    - name: Start Ollama Service
      run: |
        echo "Starting Ollama service..."
        ollama serve &
        sleep 5
        echo "Verifying Ollama service is running..."
        curl http://127.0.0.1:11434 || (echo "Ollama service not responding" && exit 1)

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow

    - name: Run Script to Generate and Send Email
      env:
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        EMAIL_LOGIN: ${{ secrets.EMAIL_LOGIN }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python generate_and_send_email.py

    - name: Configure Git for Commit
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and Push Changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git remote set-url origin https://github-actions:${{ secrets.PAT }}@github.com/edwardlorilla1986/quotes.git
        git add Post/post.png
        git commit -m "Add daily quote image"
        git push origin HEAD:main
